name: GitHub Actions Demo
on: [push]
jobs:
  Sample-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ My name is Sara Zamir."
      - run: echo "ğŸ§ I am studying Devops from Sir Saiem"
